[features]
seeds = false
skip-lint = false
[programs.localnet]
on_chain_program = "LFnX9eor6aBpmMdcF1QqWcbf2q6doTkvAYUxAGtq3MP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kar/.config/solana/id.json"

[scripts]
test = "pnpm run test"
